# Generated by Django 3.2 on 2022-06-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user_tag', models.TextField(blank=True, null=True)),
                ('hash_tag', models.TextField()),
                ('username', models.CharField(max_length=5)),
                ('like', models.IntegerField()),
                ('report', models.IntegerField()),
            ],
        ),
    ]
