# Generated by Django 3.2 on 2022-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmemory',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
