# Generated by Django 3.2 on 2022-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_addmemory_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmemory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
